#!/usr/bin/env python3
"""Build the Sage API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Sage Family',
        "color": '#00DC06',
        "closed": True,
        "stations": [
        ('Accounting', (640, 260)),
        ('Intacct', (830, 398)),
        ('Sage X3', (758, 622)),
        ('Sage 200', (522, 622)),
        ('Sage 50', (450, 398)),
        ],
    },
]

URL_OVERRIDES = {
    'Accounting': 'https://apis.apis.io/apis/sage/accounting/',
    'Intacct': 'https://apis.apis.io/apis/sage/intacct/',
    'Sage X3': 'https://apis.apis.io/apis/sage/sage-x3/',
    'Sage 200': 'https://apis.apis.io/apis/sage/sage-200/',
    'Sage 50': 'https://apis.apis.io/apis/sage/sage-50/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Sage API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: sage/openapi · github.com/api-evangelist/sage',
        out_dir=Path(__file__).resolve().parent,
        out_basename='sage-subway-map',
        provider_id='sage',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
